Repository cse110-sp24-group20/cse110-sp24-group20, pull requests merged in 2024-06, with the labels that each got.

#148 Update backgrounds
  img/backgrounds/earth.jpg
  img/backgrounds/earth.svg
  img/backgrounds/jupiter-dark.jpg
  img/backgrounds/jupiter-light.jpg
  img/backgrounds/mars.png
  img/backgrounds/mars.svg
  img/backgrounds/neptune (1).png
  img/backgrounds/neptune.svg
  src/css/daySchedule.css
  src/css/monthSchedule.css
  src/css/projectTracker.css
  src/css/reflectDay.css
Labels: design

#165 Update GitHub Pages Link in README
  README.md
Labels: github

#172 Compress backgrounds
  img/backgrounds/earth.jpg
  img/backgrounds/jupiter-light.jpg
  img/backgrounds/mars.jpg
  img/backgrounds/neptune (1).png
  img/backgrounds/space.jpg
  index.html
  src/css/daySchedule.css
  src/css/index.css
  src/html/monthSchedule.html
  src/javascript/index.js
Labels: enhancement, design

#187 Update daySchedule.css
  src/css/daySchedule.css
Labels: CSS

#190 Create e2e.yml
  .github/workflows/e2e.yml
Labels: CSS
